**Classification of Iris Flowers Using their petal, sepal lenght and width.**


Importing main libraries

In [ ]:
import pandas as pd 
import numpy as np

Importing iris data from sklearn library

In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [ ]:
print("keys of iris_dataset: \n{}".format(iris_dataset.keys()))

keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Looking what each key holds values/details for

1] DESCR (Description)
      Printing instances and attributes

In [ ]:
val = iris_dataset['DESCR']
start_val = val[:200]
print(start_val+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


2] Target_names: 
     Describing and printing names of flower

In [ ]:
print("target names: {}".format(iris_dataset['target_names']))

target names: ['setosa' 'versicolor' 'virginica']


3] Feature_names : describing mathematically measurement of flowers petal and sepal

In [ ]:
print("feature names: \n {}".format(iris_dataset['feature_names']))

feature names: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


4] Data

This code will tell us the type of class

In [ ]:
print("type of data: {}".format(type(iris_dataset['data'])))

type of data: <class 'numpy.ndarray'>


The below code will give us the row and column i.e flowers and their measurments resp.

In [ ]:
print("shape of data: {}".format(iris_dataset['data'].shape))

shape of data: (150, 4)


Printing the first five rows of data

In [ ]:
print("first five rows of data:\n{}".format(iris_dataset['data'][:5]))

first five rows of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


5]  Target (which species it belongs to)


In [ ]:
print("type of target: {}".format(type(iris_dataset['target'])))

type of target: <class 'numpy.ndarray'>


In [ ]:
print("shape of target: {}".format(iris_dataset['target'].shape))

shape of target: (150,)


Representation for flowers= 
0: setosa
1: versicolor 
2: virginica

In [ ]:
print("target:\n{}".format(iris_dataset['target']))

target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Importing from sklearn and  Now Adding a framework to split the data in 2 parts

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
                    iris_dataset['data'],iris_dataset['target'],random_state=0)

Now seeing the shapes

In [ ]:
print("x_train shape: {}".format(x_train.shape))
print("y_train shape:{}".format(y_train.shape))
print("x_test shape: {}".format(x_test.shape))
print("y_test shape:{}".format(y_test.shape))

x_train shape: (112, 4)
y_train shape:(112,)
x_test shape: (38, 4)
y_test shape:(38,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Now after creating the modle we have to now train it by using fit function 

In [ ]:
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
x_new = np.array([[5,2.9,1,0.2]])
print("x_new.shape: {}".format(x_new.shape))

x_new.shape: (1, 4)


Now Making pridiction at that data point

In [ ]:
prediction = knn.predict(x_new)

print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
                                      iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


Now after completing the training process now we have to test the modle

In [ ]:
y_pred = knn.predict(x_test)
print("test set predictions: \n{}".format(y_pred))

test set predictions: 
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [ ]:
print("test set score: {}".format(np.mean(y_pred== y_test)))

test set score: 0.9736842105263158
